sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234

  alioss:
    endpoint:  oss-cn-beijing.aliyuncs.com
    access-key-id:  LTAI5t7ZSRzfi6oCmYKiJDxA
    access-key-secret:  i9I7wHCgKlRGwMjPlztEaejyNPWnLR
    bucket-name: java-ai-tinas

  wechat:
    appid: wx88317ac0ebc0b02a
    secret: 5e4aa62d7f0bac1a7c5a01fb711fdc55
#    mchid: wxff0f0a6c9f0e64a0
#    mchSerialNo: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtw9eZ
#    privateKeyFilePath: classpath:wechat_pay/apiclient_key.pem
#    apiV3Key: 7v6a76669z4z99999999999999999999
#    weChatPayCertFilePath: classpath:wechat_pay/apiclient_cert.pem
#    notifyUrl: http://localhost:8080/wechat/notify
#    refundNotifyUrl: http://localhost:8080/wechat/refund-notify
